// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ogrenci_Ders_Secimi.Models;

namespace Ogrenci_Ders_Secimi_1.Migrations
{
    [DbContext(typeof(OgrenciDersSabahContext))]
    partial class OgrenciDersSabahContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumBaskani")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.BolumDers", b =>
                {
                    b.Property<int>("BolumDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.HasKey("BolumDersId");

                    b.HasIndex("BolumId");

                    b.HasIndex("DersId");

                    b.ToTable("BolumDersler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersDonemi")
                        .HasColumnType("int");

                    b.Property<int>("DersKredi")
                        .HasColumnType("int");

                    b.Property<string>("DersOgretmeni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DersId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OgrenciDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciDonemi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OgrenciKayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciSoyAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciDersId");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.BolumDers", b =>
                {
                    b.HasOne("Ogrenci_Ders_Secimi_1.Models.Bolum", "Bolum")
                        .WithMany("BolumDersler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ogrenci_Ders_Secimi_1.Models.Ders", "Ders")
                        .WithMany("BolumDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Ogrenci", b =>
                {
                    b.HasOne("Ogrenci_Ders_Secimi_1.Models.Bolum", null)
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumId");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.OgrenciDers", b =>
                {
                    b.HasOne("Ogrenci_Ders_Secimi_1.Models.Ders", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ogrenci_Ders_Secimi_1.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Bolum", b =>
                {
                    b.Navigation("BolumDersler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Ders", b =>
                {
                    b.Navigation("BolumDersler");

                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("Ogrenci_Ders_Secimi_1.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
